name: Go CI Pipeline

on:
  pull_request:
    branches:
      - develope
      - main
  push:
    branches:
      - develope

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4

      - name: Set Environment Variables
        env:
            PIPEDRIVE_API_TOKEN: ${{ secrets.PIPEDRIVE_API_TOKEN }}
            PIPEDRIVE_API_URL: ${{ secrets.PIPEDRIVE_API_URL }}
        run: |
            echo "PIPEDRIVE_API_TOKEN is set"

      - name: Run static analysis (go vet)
        run: go vet ./...

      - name: Check formatting (gofmt)
        run: gofmt -d . || true

      - name: Run tests
        env:
          PIPEDRIVE_API_TOKEN: ${{ secrets.PIPEDRIVE_API_TOKEN }}
          PIPEDRIVE_API_URL: ${{ secrets.PIPEDRIVE_API_URL }}
          
        run: go test ./...

      - name: Build project
        run: go build -v ./...
