# test2
name: Go CI Pipeline

on:
  push:
    branches:
      - develope
      - main
  pull_request:
    branches:
      - develope
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4

      - name: Set Environment Variables
        env:
            PIPEDRIVE_API_TOKEN: ${{ secrets.PIPEDRIVE_API_TOKEN }}
        run: |
            echo "PIPEDRIVE_API_TOKEN is set"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          # key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          key: ${{ runner.os }}-go-${{ github.run_id }}

          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build project
        run: go build -v ./...

      - name: Run static analysis (go vet)
        run: go vet ./...

      - name: Check formatting (gofmt)
        run: gofmt -d . || true

      - name: Run tests
        env:
          PIPEDRIVE_API_TOKEN: ${{ secrets.PIPEDRIVE_API_TOKEN }}
        run: go test ./...
