name: Go CI

on:
  push:
    branches:
      - develope
      - main
  pull_request:
    branches:
      - develope
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Run gofmt (format check)
        run: gofmt -d ./

      - name: Run go vet (static analysis)
        run: go vet ./...

      - name: Run golint (linting)
        run: go install golang.org/x/lint/golint@latest && golint ./...

      - name: Build project
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
